name: Run Sales Pipeline

on:
  push:
    branches:
      - main

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: pip install --upgrade databricks-cli

      - name: Run Sales Notebook Job
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          databricks jobs run-now --job-id 758363636022580
